import { THEMES, type ThemeId } from '@dosely/shared';
import { Image } from 'expo-image';
import { useState } from 'react';
import { Pressable, View } from 'react-native';
import Animated from 'react-native-reanimated';

import { icons } from '@/constants/icons';
import { buildAppTheme, CHROME_FONT_CAP, cssEasing, radius, spacing, useTheme } from '@/theme';

import { AppText } from './app-text';
import { Icon } from './icon';
import { MotifShape } from './seasonal-backdrop';

/** The alternate app icon artwork for each theme (generated by scripts/make-icons.mjs). */
const ICON_ART: Record<ThemeId, number> = {
  default: require('@/assets/icons/icon-default.png'),
  'new-year': require('@/assets/icons/icon-new-year.png'),
  valentines: require('@/assets/icons/icon-valentines.png'),
  'st-patricks': require('@/assets/icons/icon-st-patricks.png'),
  easter: require('@/assets/icons/icon-easter.png'),
  'canada-day': require('@/assets/icons/icon-canada-day.png'),
  'independence-day': require('@/assets/icons/icon-independence-day.png'),
  halloween: require('@/assets/icons/icon-halloween.png'),
  'thanksgiving-ca': require('@/assets/icons/icon-thanksgiving-ca.png'),
  'thanksgiving-us': require('@/assets/icons/icon-thanksgiving-us.png'),
  holidays: require('@/assets/icons/icon-holidays.png'),
};

export const THEME_CARD_WIDTH = 156;

export type ThemeCardProps = {
  themeId: ThemeId;
  selected: boolean;
  /** Shown as a small "Today" tag when auto-by-date currently resolves to this theme. */
  activeBadge?: string;
  onPress: () => void;
};

/**
 * A theme in the gallery: a miniature Today screen in the theme's own palette (current light/dark
 * scheme), its motif, and the matching Home Screen icon. Selecting applies instantly.
 */
export function ThemeCard({ themeId, selected, activeBadge, onPress }: ThemeCardProps) {
  const { colors, scheme } = useTheme();
  const preview = buildAppTheme(themeId, scheme);
  const p = preview.colors;
  const meta = THEMES[themeId];
  const [pressed, setPressed] = useState(false);

  return (
    <Pressable
      accessibilityRole="radio"
      accessibilityState={{ selected }}
      accessibilityLabel={`${meta.name} theme. ${meta.description}`}
      accessibilityHint="Applies the theme and its app icon"
      onPress={onPress}
      onPressIn={() => setPressed(true)}
      onPressOut={() => setPressed(false)}
    >
      <Animated.View
        style={{
          width: THEME_CARD_WIDTH,
          borderRadius: radius.md + 4,
          borderCurve: 'continuous',
          padding: 3,
          borderWidth: 2.5,
          borderColor: selected ? colors.accent : 'transparent',
          transform: [{ scale: pressed ? 0.97 : 1 }],
          transitionProperty: 'transform',
          transitionDuration: 120,
          transitionTimingFunction: cssEasing.standard,
        }}
      >
        {/* Miniature screen */}
        <View
          style={{
            height: 132,
            borderRadius: radius.md,
            borderCurve: 'continuous',
            backgroundColor: p.surface,
            overflow: 'hidden',
            padding: spacing.sm + 2,
            gap: spacing.sm,
            boxShadow: preview.shadow('sm'),
          }}
        >
          {meta.motif !== 'none' ? (
            <View pointerEvents="none" style={{ position: 'absolute', top: 8, right: 8, flexDirection: 'row', gap: 4, alignItems: 'flex-end' }}>
              <MotifShape motif={meta.motif} size={16} c={p} variant={0} />
              <MotifShape motif={meta.motif} size={11} c={p} variant={1} />
            </View>
          ) : null}
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}>
            <View style={{ width: 30, height: 30, borderRadius: 15, borderWidth: 5, borderColor: p.accent, borderTopColor: p.track }} />
            <View style={{ gap: 4 }}>
              <View style={{ width: 46, height: 6, borderRadius: 3, backgroundColor: p.text }} />
              <View style={{ width: 30, height: 5, borderRadius: 3, backgroundColor: p.textSecondary }} />
            </View>
          </View>
          <View style={{ backgroundColor: p.surfaceElevated, borderRadius: radius.sm, padding: spacing.sm, gap: 6 }}>
            <View style={{ width: '70%', height: 6, borderRadius: 3, backgroundColor: p.text }} />
            <View style={{ flexDirection: 'row', gap: 6, alignItems: 'center' }}>
              <View style={{ flex: 1, height: 18, borderRadius: 6, backgroundColor: p.accent }} />
              <View style={{ flex: 1, height: 18, borderRadius: 6, backgroundColor: p.accentSoft }} />
            </View>
          </View>
          <Image
            source={ICON_ART[themeId]}
            style={{ position: 'absolute', right: spacing.sm, bottom: spacing.sm, width: 30, height: 30, borderRadius: 7 }}
            accessible={false}
          />
        </View>

        {/* Name */}
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingHorizontal: spacing.xs, paddingTop: spacing.sm, paddingBottom: spacing.xs }}>
          <AppText variant="callout" weight="600" numberOfLines={2} maxFontSizeMultiplier={CHROME_FONT_CAP} style={{ flex: 1 }}>
            {meta.name}
          </AppText>
          {selected ? <Icon name={icons.checkCircle} size={18} color={colors.accentText} /> : null}
        </View>
        {activeBadge ? (
          <AppText variant="caption" tone="accent" maxFontSizeMultiplier={CHROME_FONT_CAP} style={{ paddingHorizontal: spacing.xs }}>
            {activeBadge}
          </AppText>
        ) : null}
      </Animated.View>
    </Pressable>
  );
}
